### ISSUE TITLE
Add support for one product_slug but multiple tiles

### ISSUE THREAD

**Issue by brightzheng100** [brightzheng100/platform-automation-pipelines#11]
There is a possibility in Pivnet that one `product_slug` can be used to serve multiple tiles, with different matching patterns for retrieving the right `glob`.

For example, in `Reliability View for PCF` (it's beta now):

```
  # Reliability View for PCF
  reliability-view:
    product-version: "0.3.0"
    pivnet-product-slug: reliability_view_pcf
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "reliability-view-[0-9]*.pivotal"
    stemcell-iaas: vsphere

  # Reliability View for PKS Exporter
  reliability-view-pks-exporter:
    product-version: "0.3.0"
    pivnet-product-slug: reliability_view_pcf
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "reliability-view-pks-exporter-*.pivotal"
    stemcell-iaas: vsphere
```

In this case, it will introduce problems based on current naming patterns:
1. The product config files, under `/generated-config` will be replaced by latter `generate-product-config` task;
2. We can't differentiate product config files for these tiles because the files under `/products` and `/vars` are with naming pattern of `<PRODUCT_SLUG>.yml`

So I'm thinking to add an optional but customizable suffix while orchestrating the pipelines.
For example:
```
#! Reliability View for PCF
- reliability-view|reliability_view_pcf|p-reliability-view

#! Reliability View Exporter for PKS
- reliability-view-pks-exporter|reliability_view_pcf|p-reliability-view|pks-exporter
```

So that the files will become:
```
/generated-config
    reliability_view_pcf.yml
    reliability_view_pcf-pks-exporter.yml
/products
    reliability_view_pcf.yml
    reliability_view_pcf-pks-exporter.yml
/vars
    reliability_view_pcf-vars.yml
    reliability_view_pcf-pks-exporter-vars.yml
```
