### ISSUE TITLE
Changing config in products.yml can't refresh the metadata and trigger new builds

### ISSUE THREAD

**Issue by brightzheng100** [brightzheng100/platform-automation-pipelines#12]
The design is to embrace GitOps, by monitoring the `<PLATFORM_CODE>/products.yml`, so that any version changes can be automatically detected and handled by pipelines.

As an example:
```
  ...
  pas:
    product-version: "2.3.5"
    pivnet-product-slug: elastic-runtime
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "srt-*.pivotal"           # Glob pattern for small-footprint PAS
    stemcell-iaas: google

  ...
```
> Note: For a complete yaml file, please check out [here](
https://github.com/brightzheng100/platform-automation-configuration/blob/master/pez/products.yml)

But there is still a case, we don't change the version itself, instead, we change the config contents.

For example, we've already configured PAS like above code snippet and have flied the pipeline and run through some Jobs, but we realize that it's a wrong config as we're going to setup a full-fledged PAS (instead of small-footprint PAS).

So we made the change, as:
```
  ...
  pas:
    product-version: "2.3.5"
    pivnet-product-slug: elastic-runtime
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "cf-*.pivotal"           # Glob pattern for full fledged PAS
    stemcell-iaas: google

  ...
``` 

This would cause a problem, as Concourse can't refresh the metadata as it would consider it's the same version as `2.3.5`.
